---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodmart-db2
  labels:
    name: foodmart-db2
spec:
  selector:
    matchLabels:
      app: foodmart-db2
  replicas: 1
  template:
    metadata:
      labels:
        app: foodmart-db2
    spec:
      containers:
      - name: foodmart-db2
        image: "eu.gcr.io/dev-and-test-env/foodmart-db2:v0.0.1"
        env:
          - name: DB2INST1_PASSWORD
            value: jhgfkuyfkuyt7647548
        ports:
          - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: foodmart-db2
  labels:
    app: foodmart-db2
spec:
  ports:
  - port: 50000
    targetPort: 50000
    name: port1
  selector:
    app: foodmart-db2
