---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodmart-mongo
  labels:
    name: foodmart-mongo
spec:
  selector:
    matchLabels:
      app: foodmart-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: foodmart-mongo
    spec:
      containers:
      - name: foodmart-mongo
        image: "eu.gcr.io/staging-205711/foodmart-mongo:v0.0.3"
        ports:
          - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: foodmart-mongo
  labels:
    app: foodmart-mongo
spec:
  ports:
  - port: 27017
    targetPort: 39013
    name: port1
  selector:
    app: foodmart-mongo
